### ISSUE TITLE
Rewrite powershell scripts to JavaScript

### ISSUE THREAD

**Issue by Hafeok** [PentiaLabs/generator-helix#3]
The powershell scripts can be rewritten into javascript, and should be to have as few dependcies on powershell as possible. 

The powershell should be made into a module, if the functionality is needed as powershell else where.

**Comment by TakeitEasyAlan** [comment]
I am not sure this is such a good idea as power shell provides a type safe way to parse the solution file, and check against enumerations instead of guids!!! and I therefore feel it will be more future proof, if VS change their solution file structure or guids!

**Comment by Hafeok** [comment]
I would still like to get rid of the powershell dependency, because it would enable us to run this on linux or mac without having powershell installed there.

**Comment by Saturate** [comment]
I guess we could write a unit test that would ensure that powershell and the javascript did the same thing - and if in the future it changes, it will notify us with a failed test?

**Comment by saberone** [comment]
@Hafeok Have you tried installing Powershell on Linux/macOS? https://github.com/PowerShell/PowerShell Powershell can be installed on does platforms too.

And might I ask why you'd like to run the script from the other platforms, since Sitecore and Visual Studio 2013/2017 do not run from Linux/macOS. It might become more interesting as Sitecore will fully run on dotnet core.

**Comment by Hafeok** [comment]
@saberone i havnt tried running it on powershell for linux. The use case that i would like to have is that i can run it through a container preferrably a small unix one, so that people dont have to rely on a specific version of powershell. Then it would be possible for us to have just a container where its run from and through. 

Other than that, i like to have as few dependencies to a tool as possible, and what we are doing in powershell isnt really that complicated.

**Comment by TakeitEasyAlan** [comment]
But what we do in power-shell ensures that it is type safe, and we don't have to compare against magic guids!!!

**Comment by saberone** [comment]
@TakeitEasyAlan Wait a minute, magic guids are part of the Sitecore Life&trade;

Seriously though. I have a love-hate relationship with Powershell. And currently I'm using Cake for my build script. So that's one less language that I need to get used to. So ideally I wouldn't need Powershell or Gulp/Grunt/Whatever for building/packaging. At least not the .NET code. Front end code is another beast.

**Comment by TakeitEasyAlan** [comment]
Closing this for now, until we hear from the hordes of Linux/Mac-using Sitecore developers craving JS-only ;)
