### ISSUE TITLE
Custom console questions and actions

### ISSUE THREAD

**Issue by snyhde** [PentiaLabs/generator-helix#69]
As a developer I'd like to add custom questions to the Helix console when a developer is adding a new project or solution.

It would be nice to be able to call a library of predefined system methods, and in the long term extend with you own custom methods. 

It could be json formatted configuration:
```

{
   "questions": [
   {
      "question": {
         "title": "Include files as part of visual studio?",
         "options": [ 
         {
	    "title": "Yes", 
            "action": "DoAttachAllFilesToVisualStudio()"
         },
         {
	    "title": "No", 
            "action": "NoAction()"
         }  
         ]
      }, 
      "question": {
         "title": "Some other question?",
         "options": [ 
         {
	    "title": "Yes", 
            "action": "DoSomeOtherQuestionMethodAlternativeYes()"
         },
         {
	    "title": "No", 
            "action": "DoSomeOtherQuestionMethodAlternativeNo()"
         }  
         ]
      }
  ]
}
```

**Comment by Hafeok** [comment]
What exactly is it that you need? - the include files in visual studio are covered right now as part of the extension model for the add generator. If you have other specific needs then create issues for those. This sort of extension model, is out of scope for this generator. 

else you can take a look at composing this generator with one of your own creation. 
http://yeoman.io/authoring/composability.html

Closing this issue - since its out of scope right now.
